### ISSUE TITLE
Read and change all your data on websites you visit

### ISSUE THREAD

**Issue by tikolakin** [rdbrck/jira-template-injector#33]
Why were permissions changed so weird?
https://prnt.sc/fc07bx

**Comment by cfoucher** [comment]
We got a bunch of "Does not work" reviews in the chrome webstore. In an attempt to make the extension work right out of the box, we are now reloading any open *.atlassian.net pages on first install so that the extension gets properly loaded. In order to do this we needed to add the "tabs" permission, which appears to cause this warning.

We do not read anything on any of your pages other than the *.atlassian.net pages (and only what is required to inject the template).

Cheers
