### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by waxidiotic** [rdbrck/jira-template-injector#50]
Love your extension in Chrome, but was wondering if you plans to port it over to Firefox?

**Comment by cfoucher** [comment]
Hi @waxidiotic,

We have been wanting to port the extension over to Firefox. While we don't have an immediate timeframe for this, it is definitely something we are looking into. 

That's for the feedback!

**Comment by kenosan** [comment]
Would really appreciate a Firefox port, this extension saved my team tons of time and increased our productivity!

**Comment by aaronr93** [comment]
Any update on this? It would be a godsend!

**Comment by dickalexei** [comment]
+1 On this!

**Comment by jhernandezinzunzaTechtonic** [comment]
Same

**Comment by seansfkelley** [comment]
I did some spelunking here to figure out how hard it would be. The only problem seems to be around Content Security Policy, for which [Firefox is very strict about for extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy). Firefox assigns a [default CSP of `script-src 'self'; object-src 'self';`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy#Default_content_security_policy).

I was able to get the addon to function by 

1. Extracting the inline script in `sandbox.html` out to a file that is then loaded into the HTML, thereby having it safely pass Firefox's default CSP. (I'll get to why I didn't change the CSP in a second.)
2. I changed the CSP in the extension with the `content_security_policy` manifest key to `script-src 'self' 'unsafe-eval'; object-src 'self;` because Handlebars uses the `Function` constructor.

After those changes, the extension worked, but is [not legal for addons.mozilla.org](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy):

> ...extensions with 'unsafe-eval', 'unsafe-inline', remote script, blob, or remote sources in their CSP are not allowed for extensions listed on addons.mozilla.org due to major security issues.

So the real heart of the fix here is going to be to see if there's a alternate build or newer version of Handlebars that doesn't something banned by the lack of `unsafe-eval`.

Secondarily, I was surprised to find that your use of `chrome = browser;` actually worked. The Firefox versions of the WebExtension APIs use Promises, not callbacks, or so the docs state. But in my version of Firefox (71.0), the current callback-heavy code seemed to work just fine. Go figure. FWIW, I use the excellent [`chrome-extension-async`](https://www.npmjs.com/package/chrome-extension-async) in my own code to bridge the API gap between Chrome and Firefox, and use Promises everywhere I talk to the browser APIs. Never had a problem with browser compatibility since.

**Comment by rhodessteve** [comment]
@seansfkelley So is there a way we can get this working by modifying things manually and packaging it ourselves? I know this wouldnt be able to be hosted on addons.mozilla.org but we would be able to have a working addon if you could provide more detailed instructions.

**Comment by seansfkelley** [comment]
Assuming nothing has changed in the year since I wrote that comment, yes, you can just follow those instructions and then zip up the result and distribute it however you'd like. As I haven't used this extension in months, I don't have any more detail to provide than what's already outlined there.
